# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
include:
  # - board: splinky
  #   shield: splinktegrated charybdis_left
  # - board: splinky
  #   shield: splinktegrated charybdis_right
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y

  # - board: splinky
  #   shield: splinktegrated scylla_left
  # - board: splinky
  #   shield: splinktegrated scylla_right
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y

  # - board: splinky
  #   shield: splinktegrated charybdis_mini_left
  # - board: splinky
  #   shield: splinktegrated charybdis_mini_right
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y

  # - board: splinky
  #   shield: splinktegrated tbkmini_left
  # - board: splinky
  #   shield: splinktegrated tbkmini_right
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: splinky
    shield: splinktegrated charybdis_nano_left
  - board: splinky
    shield: splinktegrated charybdis_nano_right
    snippet: zmk-usb-logging


  # - board: splinky
  #   shield: splinktegrated skeletyl_left
  # - board: splinky
  #   shield: splinktegrated skeletyl_right
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y
